// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2180.Guppy;

import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static CANTalon robotchassis1;
	public static CANTalon robotchassis2;
	public static CANTalon shooterCANTalon;
	public static RobotDrive Chassis;
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	 robotchassis1 = new CANTalon(30);
         LiveWindow.addActuator("RobotChassis", "CAN Talon 1", robotchassis1);
         
         robotchassis2 = new CANTalon(31);
         LiveWindow.addActuator("RobotChassis", "CAN Talon 2", robotchassis2);
         
         shooterCANTalon = new CANTalon(21);
         LiveWindow.addActuator("Shooter", "CAN Talon 3", shooterCANTalon);
         
         Chassis = new RobotDrive(robotchassis1, robotchassis2);
         
         Chassis.setSafetyEnabled(true);
         Chassis.setExpiration(0.1);
         Chassis.setSensitivity(0.5);
         Chassis.setMaxOutput(1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
